version: '2.12'

services:
  ui-dev:
    build:
      context: ../../
      dockerfile: builder/dev-site/Dockerfile
    container_name: ui-dev
    command: sh ./builder/dev-site/docker_entry_point.sh
    restart: unless-stopped
    volumes:
      - ../../:/code
    ports:
      - "${RUNNING_PORT}:${CONTAINER_PORT}"
    env_file:
      - ../../.env
    networks:
      - docker_network_cloud

networks:
  docker_network_cloud:
    external: true
