version: '2.12'

services:
  ui-sit:
    build:
      context: ../../
      dockerfile: builder/Dockerfile
    container_name: ui-sit
    command: sh ./builder/docker_entry_point.sh
    restart: unless-stopped
    volumes:
      - ../../:/code
      - ../../static:/code/static
    ports:
      - "${RUNNING_PORT}:8000"
    env_file:
      - ../../.env
    networks:
      - docker_network_cloud

networks:
  docker_network_cloud:
    external: true
